language: csharp
os: linux
dist: trusty
sudo: required
dotnet: 2.1.3
mono: none
env: DOTNETCORE=1
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
script:
  - chmod +x ./deploy-envs.sh
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "realeases/release_1_0_0" ]; then ./deploy.sh; fi